# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p10.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='p10.proto',
  package='p10',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tp10.proto\x12\x03p10\"*\n\x07\x43s10800\x12\r\n\x05State\x18\x01 \x02(\r\x12\x10\n\x08Platform\x18\x02 \x02(\t\"\x81\x01\n\x07Sc10801\x12\x11\n\tGatewayIp\x18\x01 \x02(\t\x12\x13\n\x0bGatewayPort\x18\x02 \x02(\r\x12\x0b\n\x03Url\x18\x03 \x02(\t\x12\x0f\n\x07Version\x18\x04 \x03(\t\x12\x0f\n\x07ProxyIp\x18\x05 \x01(\t\x12\x11\n\tProxyPort\x18\x06 \x01(\r\x12\x0c\n\x04IsTs\x18\x07 \x02(\r'
)




_CS10800 = _descriptor.Descriptor(
  name='Cs10800',
  full_name='p10.Cs10800',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='State', full_name='p10.Cs10800.State', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Platform', full_name='p10.Cs10800.Platform', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=60,
)


_SC10801 = _descriptor.Descriptor(
  name='Sc10801',
  full_name='p10.Sc10801',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='GatewayIp', full_name='p10.Sc10801.GatewayIp', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='GatewayPort', full_name='p10.Sc10801.GatewayPort', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Url', full_name='p10.Sc10801.Url', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Version', full_name='p10.Sc10801.Version', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ProxyIp', full_name='p10.Sc10801.ProxyIp', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ProxyPort', full_name='p10.Sc10801.ProxyPort', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='IsTs', full_name='p10.Sc10801.IsTs', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=192,
)

DESCRIPTOR.message_types_by_name['Cs10800'] = _CS10800
DESCRIPTOR.message_types_by_name['Sc10801'] = _SC10801
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cs10800 = _reflection.GeneratedProtocolMessageType('Cs10800', (_message.Message,), {
  'DESCRIPTOR' : _CS10800,
  '__module__' : 'p10_pb2'
  # @@protoc_insertion_point(class_scope:p10.Cs10800)
  })
_sym_db.RegisterMessage(Cs10800)

Sc10801 = _reflection.GeneratedProtocolMessageType('Sc10801', (_message.Message,), {
  'DESCRIPTOR' : _SC10801,
  '__module__' : 'p10_pb2'
  # @@protoc_insertion_point(class_scope:p10.Sc10801)
  })
_sym_db.RegisterMessage(Sc10801)


# @@protoc_insertion_point(module_scope)
